### ISSUE TITLE
Can not import pywwt

### ISSUE THREAD

**Issue by qu123xxx** [WorldWideTelescope/pywwt#267]
Hi! I find I can not import `pywwt 0.8.0` with `astropy 4.0.1.post1` ,` reproject 0.6` in `python 3.6,` `Windows 10 x64`

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "D:\Tools\Visual Studio 2017\Shared\Python36_64\lib\site-packages\pywwt\__init__.py", line 2, in <module>
>     from .core import *  # noqa
>   File "D:\Tools\Visual Studio 2017\Shared\Python36_64\lib\site-packages\pywwt\core.py", line 10, in <module>
>     from .annotation import Circle, Polygon, Line, FieldOfView, CircleCollection
>   File "D:\Tools\Visual Studio 2017\Shared\Python36_64\lib\site-packages\pywwt\annotation.py", line 9, in <module>
>     from .utils import validate_traits
>   File "D:\Tools\Visual Studio 2017\Shared\Python36_64\lib\site-packages\pywwt\utils.py", line 7, in <module>
>     from reproject import reproject_interp
>   File "D:\Tools\Visual Studio 2017\Shared\Python36_64\lib\site-packages\reproject\__init__.py", line 13, in <module>
>     from .interpolation import reproject_interp  # noqa
>   File "D:\Tools\Visual Studio 2017\Shared\Python36_64\lib\site-packages\reproject\interpolation\__init__.py", line 5, in <module>
>     from .high_level import *  # noqa
>   File "D:\Tools\Visual Studio 2017\Shared\Python36_64\lib\site-packages\reproject\interpolation\high_level.py", line 19, in <module>
>     order='bilinear', output_array=None, return_footprint=True):
>   File "D:\Tools\Visual Studio 2017\Shared\Python36_64\lib\site-packages\astropy\utils\decorators.py", line 443, in decorator
>     param = arguments[old_name[i]]
> KeyError: 'independent_celestial_slices'

**Comment by qu123xxx** [comment]
issue solved. It need to upgrade `reproject` to `0.7.1`
